feat: 엔티티 설계 및 프로젝트 폴더 구조 생성
Bob-Mate/BobMate-Server pull request #1
Opened 2024-01-13 05:14 UTC by lotuxsoo

<ERD랑 다른 부분>
Genre랑 Emotion을 Enum 클래스로 추가했습니다.
그리고 Content 엔티티에 genre(enum), emotion(enum) 필드 추가했습니다.
Preference 엔티티는 값타입으로 작성해보았는데 Member와 @ManyToOne 매핑이 될 수 없어서 @Embeddable 없이 작성했습니다.

2024-01-13 15:10 UTC, 5jisoo reviewed
아래 사항 확인해보시고, 궁금한 점 있으면 코멘트 달아주세요~~
- 틀린 게 있을 수도... 😅

2024-01-13 15:10 UTC, 5jisoo commented on src/main/java/com/umc/bobmate/member/domain/Member.java
> +
그 콘텐츠 선호도 값 타입 부분은 그냥 String List 라서.. 아래처럼 작성하면 자동으로 테이블 생성됩니다

```java
    @ElementCollection(fetch = LAZY)
    @CollectionTable(
            name = "Preference",
            joinColumns = @JoinColumn(name = "memberId")
    )
    @Column(name = "memo")
    private List<String> preferenceList = new ArrayList<>();
```

이런식으로 해주면 제가 알기론 되는 걸로 알고 있는데 저도 돌려본게 아니고 이전프로젝트에서 가져온거라..;
함 보긴 해야할 것 같아요 ㅎㅎ
- 참고 [값 타입 컬렉션](https://devhan.tistory.com/174)

2024-01-13 15:10 UTC, 5jisoo commented on src/main/java/com/umc/bobmate/preference/domain/Preference.java
이부분 Member.java에 코멘트 달아 놓았습니다

2024-01-13 15:12 UTC, 5jisoo commented on src/main/java/com/umc/bobmate/content/domain/Content.java
> +    private Emotion emotion;
아 이거 빼먹어서 다시 작성합니다 그 장르는 Content랑 항상 일치할 수는 있는데 감정은 항상 일치하지 않을 것 같아서..! 이 부분은 빼야할..수도 있을 것 같아요

2024-01-14 02:36 UTC, lotuxsoo commented on src/main/java/com/umc/bobmate/HelloController.java
서버 돌아가는거 확인하려고 썼는데 지우는 거 깜박했네요ㅎㅎ

2024-01-14 02:36 UTC, lotuxsoo commented on src/main/java/com/umc/bobmate/comment/domain/Comment.java
> +    @ColumnDefault("NULL")
넵!!

2024-01-14 02:37 UTC, lotuxsoo commented on src/main/java/com/umc/bobmate/comment/domain/Comment.java
> +    @ManyToOne
넵

2024-01-14 02:39 UTC, lotuxsoo commented on src/main/java/com/umc/bobmate/content/domain/ContentType.java
> +@Getter
Enum에 @Getter쓰는 방식을 봐서 적용해봤는데 static import가 더 좋은 방식 같네요 ㅎㅎ

2024-01-14 03:04 UTC, lotuxsoo commented on src/main/java/com/umc/bobmate/common/BaseEntity.java
> +    private BaseEntityStatus status = BaseEntityStatus.ACTIVE;
호오 반영했습니다!

2024-01-14 04:15 UTC, lotuxsoo commented on src/main/java/com/umc/bobmate/comment/domain/Comment.java
> +@AllArgsConstructor
엔티티에 @Builder를 쓰면
@Builder
@NoArgsConstructor
@AllArgsConstructor
이렇게 쓰거나 
@Builder 붙이고 파라미터 모두 받는 생성자 전부 작성하는 방식을 쓰더라구요

@AllArgsConstructor 대신 @Builder로 생성자 전부 쓰는게 나은 방식일까요??

2024-01-14 04:18 UTC, lotuxsoo commented on src/main/java/com/umc/bobmate/comment/domain/Comment.java
> +@AllArgsConstructor
필요없다고 하신게 @AllArgsConstructor 맞죠?
나중에 Response나 Request 엔티티에서 @Builder 쓸수있을거 같아서 붙여놨는데 일단 빼겠습니다!

2024-01-14 04:35 UTC, lotuxsoo commented on src/main/java/com/umc/bobmate/common/BaseEntity.java
> +public abstract class BaseEntity {
넹 BaseEntity에만 해당 어노테이션 추가해놓을게요

2024-01-14 04:35 UTC, lotuxsoo commented on src/main/java/com/umc/bobmate/comment/domain/Comment.java
> +@NoArgsConstructor
네네!

2024-01-14 04:35 UTC, lotuxsoo commented on src/main/java/com/umc/bobmate/comment/domain/Comment.java
> +@NoArgsConstructor
넵

2024-01-14 04:41 UTC, lotuxsoo commented on src/main/java/com/umc/bobmate/member/domain/Member.java
> +
오오 이렇게 쓰는군요.. 적용했습니다!

2024-01-14 04:45 UTC, lotuxsoo commented on src/main/java/com/umc/bobmate/content/domain/Content.java
> +    private Emotion emotion;
Emotion이랑 Genre를 이렇게 주셔서 Content 엔티티 필드에 Emotion 필드 하나랑 List<Genre> 필드를 가지는걸로 고쳐야 한는지 고민이 되네요
기쁨: 코미디, 애니메이션, 로맨스
즐거움: 모험, 로맨틱 코미디, 액션
우울: 드라마, 액션, 애니메이션
분노: 액션, 스릴러, 범죄
슬픔: 드라마, 멜로, 가족 영화

2024-01-14 07:27 UTC, 5jisoo commented on src/main/java/com/umc/bobmate/comment/domain/Comment.java
> +@AllArgsConstructor
아 맞아요 ~~ Builder 쓸 때는 그냥 따로 필요할 때마다 아래 쓰는 게 나을 것 같아서요!

2024-01-17 09:43 UTC, 5jisoo requested changes
그 값타입 제외한 양방향 매핑 @OneToMany 부분들은 필요할때 추가합시다! 지금은 굳이 필요 없을 것 같아요~

2024-01-18 18:32 UTC, 5jisoo approved these changes

2024-01-18 18:32 UTC, merged