Feat/#2 recommend contents 구현 완료
Bob-Mate/BobMate-Server pull request #10
Opened 2024-02-06 21:43 UTC by hwnooy

2024-02-07 16:42 UTC, 5jisoo requested changes
아래 수정사항 반영해주세요~~

2024-02-07 16:42 UTC, 5jisoo commented on build.gradle
빌드 그래들은 왜..? 설정 파일이라 이거 주석처리하면 안돌아가지 않아요?

2024-02-07 16:42 UTC, 5jisoo commented on src/main/java/com/umc/bobmate/like/dto/LikesDto.java
엔티티가 포함된 DTO인 것 같은데.. 이거 어디에 쓰이는 거죠?

2024-02-07 17:55 UTC, hwnooy commented on build.gradle
develop이랑 뭔가 조금 달라서 원래 제 코드 주석처리하고 그 아래에 넣고 돌렸습니다. 주석빼겠습니다

2024-02-07 17:57 UTC, hwnooy commented on src/main/java/com/umc/bobmate/like/dto/LikesDto.java
아 이거 쓰이지 않습니다! 1월에 만든게 남아있네요.. 파일 삭제하겠습니다

2024-02-08 04:59 UTC, lotuxsoo approved these changes

2024-02-08 05:20 UTC, merged